### PR TITLE
Make it possible to tap errors and completions

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by krawaller** [comment]
Hey, neat! Love it! :)

Do you want to try your hand at throwing in some tests for that, or want me to do it?

**Comment by Andarist** [comment]
Can write tests some time later 😉 will ping you when i'm done

**Comment by Andarist** [comment]
@krawaller done, just copied existing test, modified slightly - i think it's enough, if u want some other tests, let me know

**Comment by krawaller** [comment]
Doh, just realised - I've made a much smoother v2 of `callbag-mock`, should've updated the other tests before asking you to do that. Forgot I hadn't updated this package yet. Sorry! :)

But that looks great, thank you @Andarist!

**Comment by krawaller** [comment]
Published as `1.1.0`!

**Pull request merged**
